# Generated by Django 6.0.4 on 2026-09-13 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('cnic', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('current_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('education', models.JSONField(blank=True, default=list)),
                ('total_experience', models.CharField(blank=True, max_length=50)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('work_types', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('programming_languages', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('cv_file', models.FileField(upload_to='cvs/')),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_title', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('branch_code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
