# Generated by Django 6.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_last_active_at_user_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            # default='' only smooths over profiles created before this
            # field existed (so the migration doesn't fail on existing
            # rows) — CompleteProfileView still requires a real upload
            # for anyone whose profile_photo is still empty.
            field=models.FileField(default='', upload_to='avatars/'),
        ),
    ]
