# Generated by Django 6.1.1

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv_file',
            field=models.FileField(upload_to=users.models.user_cv_upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.FileField(default='', upload_to=users.models.user_photo_upload_path),
        ),
    ]
