# Generated by Django 6.1.1 on 2026-09-16 17:02

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userpage_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration_photo',
            field=models.FileField(blank=True, null=True, upload_to=users.models.user_photo_upload_path),
        ),
    ]
