# Generated by Django 6.1.1

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_wsticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            # Self-editable avatar any account can set from Settings —
            # independent of Profile.profile_photo, which requires a
            # completed Profile (CompleteProfilePage) that not every
            # account (e.g. admin) ever has. See UpdateOwnProfileView.
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_avatar_upload_path),
        ),
    ]
