# Generated by Django 6.1.1 on 2026-09-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_zip_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='unlocked',
            field=models.BooleanField(default=True),
        ),
    ]
