# Generated by Django 6.1.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subtasks',
                to='projects.module',
            ),
        ),
    ]
