# Generated by Django 6.1.1 on 2026-09-17 07:48

import django.db.models.deletion
import expenses.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('project', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('payment', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('Cash in Hand', 'Cash in Hand')], default='Cash', max_length=20)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to=expenses.models.expense_receipt_path)),
                ('receipt_name', models.CharField(blank=True, default='', max_length=255)),
                ('receipt_content_type', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['category'], name='expenses_ex_categor_fcaba7_idx'), models.Index(fields=['project'], name='expenses_ex_project_6b0b98_idx'), models.Index(fields=['status'], name='expenses_ex_status_cbb790_idx'), models.Index(fields=['date'], name='expenses_ex_date_17a2b2_idx')],
            },
        ),
    ]
