# Generated by Django 6.1.1 on 2026-09-21 09:17

import coworking.models
import coworking.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0007_modulerequest_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoworkingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=16, null=True, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=10)),
                ('application_date', models.DateField(default=django.utils.timezone.localdate)),
                ('agreement_id', models.CharField(blank=True, default='', max_length=64)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(blank=True, default='', max_length=255)),
                ('cnic', models.CharField(max_length=32)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=32)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, storage=coworking.storage.get_private_storage, upload_to=coworking.models.photo_path)),
                ('cnic_front', models.ImageField(blank=True, null=True, storage=coworking.storage.get_private_storage, upload_to=coworking.models.cnic_front_path)),
                ('cnic_back', models.ImageField(blank=True, null=True, storage=coworking.storage.get_private_storage, upload_to=coworking.models.cnic_back_path)),
                ('applicant_type', models.JSONField(blank=True, default=list)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('legal_status', models.CharField(blank=True, default='', max_length=100)),
                ('registration_no', models.CharField(blank=True, default='', max_length=100)),
                ('nature_of_work', models.CharField(blank=True, default='', max_length=255)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('chairs', models.PositiveSmallIntegerField()),
                ('rate_per_chair', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveSmallIntegerField(help_text='Months')),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('seating', models.CharField(choices=[('Dedicated', 'Dedicated'), ('Flexible / Hot Desk', 'Flexible / Hot Desk')], default='Dedicated', max_length=30)),
                ('access', models.CharField(choices=[('Office Hours', 'Office Hours'), ('Extended (if approved)', 'Extended (if approved)')], default='Office Hours', max_length=30)),
                ('assigned_chairs', models.CharField(blank=True, default='', max_length=100)),
                ('special_notes', models.TextField(blank=True, default='')),
                ('documents', models.JSONField(blank=True, default=list)),
                ('emergency_name', models.CharField(max_length=255)),
                ('emergency_relation', models.CharField(blank=True, default='', max_length=100)),
                ('emergency_phone', models.CharField(max_length=32)),
                ('emergency_alt_phone', models.CharField(blank=True, default='', max_length=32)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Card', 'Card'), ('JazzCash', 'JazzCash'), ('Easypaisa', 'Easypaisa')], default='Bank Transfer', max_length=20)),
                ('transaction_no', models.CharField(blank=True, default='', max_length=100)),
                ('billing_due_day', models.CharField(blank=True, default='5th', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Bi-Annually', 'Bi-Annually')], default='Monthly', max_length=20)),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('terms_agreed', models.BooleanField(default=False)),
                ('declaration_name', models.CharField(blank=True, default='', max_length=255)),
                ('declaration_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coworking_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CoworkingMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cnic', models.CharField(blank=True, default='', max_length=32)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('chair_no', models.CharField(blank=True, default='', max_length=50)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='coworking.coworkingapplication')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CoworkingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('approver_role', models.CharField(choices=[('CEO', 'CEO'), ('MD', 'MD'), ('Manager', 'Manager'), ('PM', 'PM'), ('Admin', 'Admin')], default='Admin', max_length=10)),
                ('approved_by', models.CharField(blank=True, default='', max_length=255)),
                ('designation', models.CharField(blank=True, default='', max_length=255)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('approved_chairs', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('approved_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approved_grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('chair_nos', models.CharField(blank=True, default='', max_length=100)),
                ('access_card_no', models.CharField(blank=True, default='', max_length=100)),
                ('wifi_issued', models.BooleanField(default=False)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='coworking.coworkingapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoworkingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='YYYY-MM the rent covers', max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Card', 'Card'), ('JazzCash', 'JazzCash'), ('Easypaisa', 'Easypaisa')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='coworking.coworkingapplication')),
                ('income', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coworking_payment', to='dashboard.income')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['application', 'month'], name='coworking_c_applica_55bace_idx')],
            },
        ),
    ]
