# Generated by Django 6.1.1 on 2026-09-22 08:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoworkingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_chairs', models.PositiveSmallIntegerField(default=12)),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=Decimal('25000'), max_digits=10)),
                ('min_duration_months', models.PositiveSmallIntegerField(default=1)),
                ('max_duration_months', models.PositiveSmallIntegerField(default=12)),
                ('duration_note', models.CharField(blank=True, default='Custom options available', max_length=100)),
                ('security_features', models.CharField(blank=True, default='Access control, CCTV', max_length=150)),
                ('support_hours', models.CharField(blank=True, default='24/7 Support', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
