# Generated by Django 6.1.1 on 2026-09-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_income_full_ledger'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='income',
            new_name='dashboard_i_status_37a742_idx',
            old_name='dashboard_i_status_5e6c8f_idx',
        ),
        migrations.RenameIndex(
            model_name='income',
            new_name='dashboard_i_project_490201_idx',
            old_name='dashboard_i_project_1a2b3c_idx',
        ),
    ]
