# Generated by Django 6.1.1 on 2026-09-20 16:04

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_client_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.client_avatar_path),
        ),
    ]
