# Generated by Django 6.1.1 on 2026-09-19 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, default='Free', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('billing_cycle', models.CharField(blank=True, default='monthly', max_length=20)),
                ('card_brand', models.CharField(blank=True, default='', max_length=30)),
                ('card_last4', models.CharField(blank=True, default='', max_length=4)),
                ('card_expiry', models.CharField(blank=True, default='', max_length=10)),
                ('storage_used_gb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('storage_limit_gb', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('street', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=120)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=120)),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=100)),
                ('currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('date_format', models.CharField(blank=True, default='MM/DD/YYYY', max_length=20)),
                ('time_format', models.CharField(blank=True, default='12h', max_length=10)),
                ('language', models.CharField(blank=True, default='en', max_length=10)),
                ('default_dashboard', models.CharField(blank=True, default='overview', max_length=50)),
                ('compact_mode', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('auto_currency_update', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.BooleanField(default=True)),
                ('push', models.BooleanField(default=True)),
                ('sms', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_key'],
                'unique_together': {('user', 'event_key')},
            },
        ),
    ]
