# Generated by Django 6.1.1 on 2026-09-30 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def apply_plan_limits(apps, schema_editor):
    """Existing installs already have a plan name saved (e.g. "Business") but the
    old default 5 GB limit and no price. Bring them in line with the catalog."""
    BillingInfo = apps.get_model("settings", "BillingInfo")
    limits = {"starter": (9999, 10), "business": (24999, 50), "enterprise": (0, 200)}
    for row in BillingInfo.objects.all():
        match = limits.get((row.plan_name or "").strip().lower())
        if match:
            row.price, row.storage_limit_gb = match
            row.save(update_fields=["price", "storage_limit_gb"])


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_company_logo_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billinginfo',
            name='next_billing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='plan', max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='Recorded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(apply_plan_limits, migrations.RunPython.noop),
    ]
