# Generated by Django 6.1.1 on 2026-09-20 07:55

import django.db.models.deletion
import django.utils.timezone
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Financial', 'Financial'), ('Project', 'Project'), ('Employee', 'Employee'), ('Client', 'Client'), ('Sales', 'Sales'), ('Task', 'Task')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('Excel', 'Excel')], default='PDF', max_length=10)),
                ('source_key', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='', max_length=255)),
                ('user_email', models.CharField(blank=True, default='', max_length=254)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.TextField(blank=True, default='')),
                ('project', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DailyReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=reports.models.daily_report_file_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('kind', models.CharField(default='image', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reports.dailyreport')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReportOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('custom_name', models.CharField(blank=True, default='', max_length=255)),
                ('hidden', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, default='', max_length=255)),
                ('actor_email', models.CharField(blank=True, default='', max_length=254)),
                ('actor_role', models.CharField(blank=True, default='', max_length=20)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('upload', 'Uploaded'), ('download', 'Downloaded'), ('export', 'Exported'), ('login', 'Logged in'), ('logout', 'Logged out'), ('login_failed', 'Failed login'), ('register', 'Registered'), ('view', 'Viewed'), ('click', 'Clicked'), ('search', 'Searched'), ('api', 'Other action')], db_index=True, max_length=20)),
                ('module', models.CharField(db_index=True, default='General', max_length=30)),
                ('object_type', models.CharField(blank=True, default='', max_length=60)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('project', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('method', models.CharField(blank=True, default='', max_length=8)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='act_user_time_idx'), models.Index(fields=['module', '-created_at'], name='act_module_time_idx'), models.Index(fields=['action', '-created_at'], name='act_action_time_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['user', '-date'], name='daily_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['status'], name='daily_status_idx'),
        ),
    ]
