# Generated by Django 6.1.1 on 2026-09-30 05:54

import django.db.models.deletion
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_dailyreportfile_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportfile',
            name='file',
            field=models.FileField(upload_to=reports.models.daily_report_file_path),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Mobile Phone', 'Mobile Phone'), ('Furniture', 'Furniture'), ('Vehicle', 'Vehicle'), ('Office Equipment', 'Office Equipment'), ('Software License', 'Software License'), ('Other', 'Other')], default='Other', max_length=30)),
                ('asset_tag', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('In Use', 'In Use'), ('Available', 'Available'), ('In Repair', 'In Repair'), ('Retired', 'Retired')], default='Available', max_length=15)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status'], name='asset_status_idx'), models.Index(fields=['assigned_to'], name='asset_assignee_idx')],
            },
        ),
    ]
