# Generated by Django 6.1.1 on 2026-09-30 06:52

import reports.models
import reports.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_dailyreportfile_file_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportfile',
            name='file',
            field=models.FileField(max_length=255, storage=reports.storage.daily_report_storage, upload_to=reports.models.daily_report_file_path),
        ),
    ]
