# Generated by Django 6.1.1 on 2026-09-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_reply_reactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10)),
                ('ref_id', models.PositiveIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('kind', 'ref_id', 'year')},
            },
        ),
    ]
