"""Country -> timezone table used by messaging/birthdays.py.

A client's birthday notification goes out at 12:00 AM in THEIR country's time.
Countries that span several timezones use their capital / main business zone.
Generated from the same country list the Clients page uses (ClientsPage.jsx).
"""

DEFAULT_TIMEZONE = "Asia/Karachi"

COUNTRY_TIMEZONES = {
    "AD": "Europe/Andorra",
    "AE": "Asia/Dubai",
    "AF": "Asia/Kabul",
    "AG": "America/Antigua",
    "AL": "Europe/Tirane",
    "AM": "Asia/Yerevan",
    "AO": "Africa/Luanda",
    "AR": "America/Argentina/Buenos_Aires",
    "AT": "Europe/Vienna",
    "AU": "Australia/Sydney",
    "AZ": "Asia/Baku",
    "BA": "Europe/Sarajevo",
    "BB": "America/Barbados",
    "BD": "Asia/Dhaka",
    "BE": "Europe/Brussels",
    "BF": "Africa/Ouagadougou",
    "BG": "Europe/Sofia",
    "BH": "Asia/Bahrain",
    "BI": "Africa/Bujumbura",
    "BJ": "Africa/Porto-Novo",
    "BN": "Asia/Brunei",
    "BO": "America/La_Paz",
    "BR": "America/Sao_Paulo",
    "BS": "America/Nassau",
    "BT": "Asia/Thimphu",
    "BW": "Africa/Gaborone",
    "BY": "Europe/Minsk",
    "BZ": "America/Belize",
    "CA": "America/Toronto",
    "CD": "Africa/Kinshasa",
    "CF": "Africa/Bangui",
    "CG": "Africa/Brazzaville",
    "CH": "Europe/Zurich",
    "CL": "America/Santiago",
    "CM": "Africa/Douala",
    "CN": "Asia/Shanghai",
    "CO": "America/Bogota",
    "CR": "America/Costa_Rica",
    "CU": "America/Havana",
    "CV": "Atlantic/Cape_Verde",
    "CY": "Asia/Nicosia",
    "CZ": "Europe/Prague",
    "DE": "Europe/Berlin",
    "DJ": "Africa/Djibouti",
    "DK": "Europe/Copenhagen",
    "DM": "America/Dominica",
    "DO": "America/Santo_Domingo",
    "DZ": "Africa/Algiers",
    "EC": "America/Guayaquil",
    "EE": "Europe/Tallinn",
    "EG": "Africa/Cairo",
    "ER": "Africa/Asmara",
    "ES": "Europe/Madrid",
    "ET": "Africa/Addis_Ababa",
    "FI": "Europe/Helsinki",
    "FJ": "Pacific/Fiji",
    "FM": "Pacific/Pohnpei",
    "FR": "Europe/Paris",
    "GA": "Africa/Libreville",
    "GB": "Europe/London",
    "GD": "America/Grenada",
    "GE": "Asia/Tbilisi",
    "GH": "Africa/Accra",
    "GM": "Africa/Banjul",
    "GN": "Africa/Conakry",
    "GQ": "Africa/Malabo",
    "GR": "Europe/Athens",
    "GT": "America/Guatemala",
    "GW": "Africa/Bissau",
    "GY": "America/Guyana",
    "HN": "America/Tegucigalpa",
    "HR": "Europe/Zagreb",
    "HT": "America/Port-au-Prince",
    "HU": "Europe/Budapest",
    "ID": "Asia/Jakarta",
    "IE": "Europe/Dublin",
    "IL": "Asia/Jerusalem",
    "IN": "Asia/Kolkata",
    "IQ": "Asia/Baghdad",
    "IR": "Asia/Tehran",
    "IS": "Atlantic/Reykjavik",
    "IT": "Europe/Rome",
    "JM": "America/Jamaica",
    "JO": "Asia/Amman",
    "JP": "Asia/Tokyo",
    "KE": "Africa/Nairobi",
    "KG": "Asia/Bishkek",
    "KH": "Asia/Phnom_Penh",
    "KI": "Pacific/Tarawa",
    "KM": "Indian/Comoro",
    "KN": "America/St_Kitts",
    "KP": "Asia/Pyongyang",
    "KR": "Asia/Seoul",
    "KW": "Asia/Kuwait",
    "KZ": "Asia/Almaty",
    "LA": "Asia/Vientiane",
    "LB": "Asia/Beirut",
    "LC": "America/St_Lucia",
    "LI": "Europe/Vaduz",
    "LK": "Asia/Colombo",
    "LR": "Africa/Monrovia",
    "LS": "Africa/Maseru",
    "LT": "Europe/Vilnius",
    "LU": "Europe/Luxembourg",
    "LV": "Europe/Riga",
    "LY": "Africa/Tripoli",
    "MA": "Africa/Casablanca",
    "MC": "Europe/Monaco",
    "MD": "Europe/Chisinau",
    "ME": "Europe/Podgorica",
    "MG": "Indian/Antananarivo",
    "MH": "Pacific/Majuro",
    "MK": "Europe/Skopje",
    "ML": "Africa/Bamako",
    "MM": "Asia/Yangon",
    "MN": "Asia/Ulaanbaatar",
    "MR": "Africa/Nouakchott",
    "MT": "Europe/Malta",
    "MU": "Indian/Mauritius",
    "MV": "Indian/Maldives",
    "MW": "Africa/Blantyre",
    "MX": "America/Mexico_City",
    "MY": "Asia/Kuala_Lumpur",
    "MZ": "Africa/Maputo",
    "NA": "Africa/Windhoek",
    "NE": "Africa/Niamey",
    "NG": "Africa/Lagos",
    "NI": "America/Managua",
    "NL": "Europe/Amsterdam",
    "NO": "Europe/Oslo",
    "NP": "Asia/Kathmandu",
    "NR": "Pacific/Nauru",
    "NZ": "Pacific/Auckland",
    "OM": "Asia/Muscat",
    "PA": "America/Panama",
    "PE": "America/Lima",
    "PG": "Pacific/Port_Moresby",
    "PH": "Asia/Manila",
    "PK": "Asia/Karachi",
    "PL": "Europe/Warsaw",
    "PS": "Asia/Gaza",
    "PT": "Europe/Lisbon",
    "PW": "Pacific/Palau",
    "PY": "America/Asuncion",
    "QA": "Asia/Qatar",
    "RO": "Europe/Bucharest",
    "RS": "Europe/Belgrade",
    "RU": "Europe/Moscow",
    "RW": "Africa/Kigali",
    "SA": "Asia/Riyadh",
    "SB": "Pacific/Guadalcanal",
    "SC": "Indian/Mahe",
    "SD": "Africa/Khartoum",
    "SE": "Europe/Stockholm",
    "SG": "Asia/Singapore",
    "SI": "Europe/Ljubljana",
    "SK": "Europe/Bratislava",
    "SL": "Africa/Freetown",
    "SM": "Europe/San_Marino",
    "SN": "Africa/Dakar",
    "SO": "Africa/Mogadishu",
    "SR": "America/Paramaribo",
    "SS": "Africa/Juba",
    "ST": "Africa/Sao_Tome",
    "SV": "America/El_Salvador",
    "SY": "Asia/Damascus",
    "SZ": "Africa/Mbabane",
    "TD": "Africa/Ndjamena",
    "TG": "Africa/Lome",
    "TH": "Asia/Bangkok",
    "TJ": "Asia/Dushanbe",
    "TL": "Asia/Dili",
    "TM": "Asia/Ashgabat",
    "TN": "Africa/Tunis",
    "TO": "Pacific/Tongatapu",
    "TR": "Europe/Istanbul",
    "TT": "America/Port_of_Spain",
    "TV": "Pacific/Funafuti",
    "TW": "Asia/Taipei",
    "TZ": "Africa/Dar_es_Salaam",
    "UA": "Europe/Kyiv",
    "UG": "Africa/Kampala",
    "US": "America/New_York",
    "UY": "America/Montevideo",
    "UZ": "Asia/Samarkand",
    "VA": "Europe/Vatican",
    "VC": "America/St_Vincent",
    "VE": "America/Caracas",
    "VN": "Asia/Ho_Chi_Minh",
    "VU": "Pacific/Efate",
    "WS": "Pacific/Apia",
    "XK": "Europe/Belgrade",
    "YE": "Asia/Aden",
    "ZA": "Africa/Johannesburg",
    "ZM": "Africa/Lusaka",
    "ZW": "Africa/Harare",
}

COUNTRY_CODE_BY_NAME = {
    'afghanistan': "AF",
    'albania': "AL",
    'algeria': "DZ",
    'andorra': "AD",
    'angola': "AO",
    'antigua and barbuda': "AG",
    'argentina': "AR",
    'armenia': "AM",
    'australia': "AU",
    'austria': "AT",
    'azerbaijan': "AZ",
    'bahamas': "BS",
    'bahrain': "BH",
    'bangladesh': "BD",
    'barbados': "BB",
    'belarus': "BY",
    'belgium': "BE",
    'belize': "BZ",
    'benin': "BJ",
    'bhutan': "BT",
    'bolivia': "BO",
    'bosnia and herzegovina': "BA",
    'botswana': "BW",
    'brazil': "BR",
    'brunei': "BN",
    'bulgaria': "BG",
    'burkina faso': "BF",
    'burundi': "BI",
    'cabo verde': "CV",
    'cambodia': "KH",
    'cameroon': "CM",
    'canada': "CA",
    'central african republic': "CF",
    'chad': "TD",
    'chile': "CL",
    'china': "CN",
    'colombia': "CO",
    'comoros': "KM",
    'congo (congo-brazzaville)': "CG",
    'congo (drc)': "CD",
    'costa rica': "CR",
    'croatia': "HR",
    'cuba': "CU",
    'cyprus': "CY",
    'czechia': "CZ",
    'denmark': "DK",
    'djibouti': "DJ",
    'dominica': "DM",
    'dominican republic': "DO",
    'ecuador': "EC",
    'egypt': "EG",
    'el salvador': "SV",
    'equatorial guinea': "GQ",
    'eritrea': "ER",
    'estonia': "EE",
    'eswatini': "SZ",
    'ethiopia': "ET",
    'fiji': "FJ",
    'finland': "FI",
    'france': "FR",
    'gabon': "GA",
    'gambia': "GM",
    'georgia': "GE",
    'germany': "DE",
    'ghana': "GH",
    'greece': "GR",
    'grenada': "GD",
    'guatemala': "GT",
    'guinea': "GN",
    'guinea-bissau': "GW",
    'guyana': "GY",
    'haiti': "HT",
    'honduras': "HN",
    'hungary': "HU",
    'iceland': "IS",
    'india': "IN",
    'indonesia': "ID",
    'iran': "IR",
    'iraq': "IQ",
    'ireland': "IE",
    'israel': "IL",
    'italy': "IT",
    'jamaica': "JM",
    'japan': "JP",
    'jordan': "JO",
    'kazakhstan': "KZ",
    'kenya': "KE",
    'kiribati': "KI",
    'kosovo': "XK",
    'kuwait': "KW",
    'kyrgyzstan': "KG",
    'laos': "LA",
    'latvia': "LV",
    'lebanon': "LB",
    'lesotho': "LS",
    'liberia': "LR",
    'libya': "LY",
    'liechtenstein': "LI",
    'lithuania': "LT",
    'luxembourg': "LU",
    'madagascar': "MG",
    'malawi': "MW",
    'malaysia': "MY",
    'maldives': "MV",
    'mali': "ML",
    'malta': "MT",
    'marshall islands': "MH",
    'mauritania': "MR",
    'mauritius': "MU",
    'mexico': "MX",
    'micronesia': "FM",
    'moldova': "MD",
    'monaco': "MC",
    'mongolia': "MN",
    'montenegro': "ME",
    'morocco': "MA",
    'mozambique': "MZ",
    'myanmar': "MM",
    'namibia': "NA",
    'nauru': "NR",
    'nepal': "NP",
    'netherlands': "NL",
    'new zealand': "NZ",
    'nicaragua': "NI",
    'niger': "NE",
    'nigeria': "NG",
    'north korea': "KP",
    'north macedonia': "MK",
    'norway': "NO",
    'oman': "OM",
    'pakistan': "PK",
    'palau': "PW",
    'palestine': "PS",
    'panama': "PA",
    'papua new guinea': "PG",
    'paraguay': "PY",
    'peru': "PE",
    'philippines': "PH",
    'poland': "PL",
    'portugal': "PT",
    'qatar': "QA",
    'romania': "RO",
    'russia': "RU",
    'rwanda': "RW",
    'saint kitts and nevis': "KN",
    'saint lucia': "LC",
    'saint vincent and the grenadines': "VC",
    'samoa': "WS",
    'san marino': "SM",
    'sao tome and principe': "ST",
    'saudi arabia': "SA",
    'senegal': "SN",
    'serbia': "RS",
    'seychelles': "SC",
    'sierra leone': "SL",
    'singapore': "SG",
    'slovakia': "SK",
    'slovenia': "SI",
    'solomon islands': "SB",
    'somalia': "SO",
    'south africa': "ZA",
    'south korea': "KR",
    'south sudan': "SS",
    'spain': "ES",
    'sri lanka': "LK",
    'sudan': "SD",
    'suriname': "SR",
    'sweden': "SE",
    'switzerland': "CH",
    'syria': "SY",
    'taiwan': "TW",
    'tajikistan': "TJ",
    'tanzania': "TZ",
    'thailand': "TH",
    'timor-leste': "TL",
    'togo': "TG",
    'tonga': "TO",
    'trinidad and tobago': "TT",
    'tunisia': "TN",
    'turkey': "TR",
    'turkmenistan': "TM",
    'tuvalu': "TV",
    'uganda': "UG",
    'ukraine': "UA",
    'united arab emirates': "AE",
    'united kingdom': "GB",
    'united states': "US",
    'uruguay': "UY",
    'uzbekistan': "UZ",
    'vanuatu': "VU",
    'vatican city': "VA",
    'venezuela': "VE",
    'vietnam': "VN",
    'yemen': "YE",
    'zambia': "ZM",
    'zimbabwe': "ZW",
}
