# Generated by Django 6.1.1 on 2026-09-23 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_module_parent'),
        ('tasks', '0002_taskzipfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.module'),
        ),
    ]
