# Generated by Django 6.1.1 on 2026-09-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_module_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client_module_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='from_client_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='sub_module_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
