from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('verify-password/', views.VerifyPasswordView.as_view(), name='verify-password'),
    path('me/', views.MeView.as_view(), name='me'),
    path('me/update/', views.UpdateOwnProfileView.as_view(), name='update-own-profile'),
    path('pending/', views.PendingUsersView.as_view(), name='pending-users'),
    path('users/', views.UsersListView.as_view(), name='users-list'),
    path('approved-users/', views.ApprovedUsersView.as_view(), name='approved-users'),
    path('users/invite/', views.InviteUserView.as_view(), name='invite-user'),
    path('users/<int:user_id>/approve/', views.ApproveUserView.as_view(), name='approve-user'),
    path('users/<int:user_id>/reject/', views.RejectUserView.as_view(), name='reject-user'),
    path('users/<int:user_id>/status/', views.SetUserStatusView.as_view(), name='set-user-status'),
    path('users/<int:user_id>/update-role/', views.UpdateUserRoleView.as_view(), name='update-user-role'),
    path('users/<int:user_id>/remove/', views.RemoveUserView.as_view(), name='remove-user'),
    path('users/<int:user_id>/profile/', views.AdminUpdateProfileView.as_view(), name='admin-update-profile'),
    path('users/<int:user_id>/assign-manager/', views.AssignManagerView.as_view(), name='assign-manager'),
    path('users/<int:user_id>/access-override/', views.UserAccessOverrideView.as_view(), name='user-access-override'),
    path('users/<int:user_id>/sub-access/<str:page>/', views.UserSubPageAccessView.as_view(), name='user-sub-access'),
    path('role-permissions/', views.RolePermissionsView.as_view(), name='role-permissions'),
    path('module-permissions/', views.ModulePermissionsView.as_view(), name='module-permissions'),
    path('settings/ai-assistant/', views.AiAssistantSettingView.as_view(), name='ai-assistant-setting'),
    path('send-otp/', views.SendOtpView.as_view(), name='send-otp'),
    path('verify-otp/', views.VerifyOtpView.as_view(), name='verify-otp'),
    path('google-login/', views.GoogleLoginView.as_view(), name='google-login'),
    path('google-signup/', views.GoogleSignupView.as_view(), name='google-signup'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='reset-password'),
    path('contact/', views.ContactMessageView.as_view(), name='contact'),
    path('complete-profile/', views.CompleteProfileView.as_view(), name='complete-profile'),
    path('ws-ticket/', views.IssueWsTicketView.as_view(), name='ws-ticket'),
]