# Generated by Django 6.1.1 on 2026-09-20 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('cnic', models.CharField(blank=True, default='', max_length=32)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('meeting_with', models.CharField(blank=True, default='', max_length=255)),
                ('purpose', models.CharField(blank=True, choices=[('Business Meeting', 'Business Meeting'), ('Interview', 'Interview'), ('Delivery / Vendor', 'Delivery / Vendor'), ('Personal Visit', 'Personal Visit'), ('Other', 'Other')], default='', max_length=32)),
                ('purpose_note', models.TextField(blank=True, default='')),
                ('appt_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Walk-in', 'Walk-in'), ('Confirmed', 'Confirmed')], default='Scheduled', max_length=16)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Waiting', max_length=10)),
                ('reviewed', models.BooleanField(default=False)),
                ('visits', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_visitors', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='visitors_vi_status_9b5b9b_idx'), models.Index(fields=['phone'], name='visitors_vi_phone_3827a1_idx')],
            },
        ),
    ]
